### ISSUE TITLE
Release 1

### ISSUE THREAD

**Issue by theaspect** [Rq0/GL_proj1#1]
- [x] 1. избавься от статиков в aaaservice

- [x] 2. тестовые данные и тесты должны совпадать с тем что выдано

- [x] 3. код не отформатирован

- [x] 4. для склеивания строк в цикле нужно использовать StringBuilder (+ нужно отчетить на вопрос почему склеивать строки плохая идея)

- [x] 5. методы с побочными эффектами если это не сеттер плохая идея https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L58

- [ ] 6. нарушает принцип единственно ответственности, класс необходимо разбить на логически связные части https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L11

- [x] 7. ты сначала в юзера записываешь пароль а потом хэшируешь? почему это нельзя сделать при создании https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L58

- [x] 8. Переписать в одну строку https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L21-L23

- [ ] 9. что будет с айдишниками если ты удалишь одного из юзеров? https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L27

- [x] 10. зачем промежуточная переменная? избавься от неё https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L43

- [x] 11. в одну строку https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L77-L78

- [x] 12. переписать на stringbuilder https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L85

- [x] 13. роль должна быть энумом https://github.com/Rq0/GL_proj1/blob/master/untitled/src/Resource.java#L7

- [x] 14. именование полей, методов не соответствует java coding conventions

- [x] 15. javadoc в методах должен быть таким /** */ (две звездочки не опечатка) https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L108

- [x] 16. в комментах к этому issue вставь фрагмент java coding conventions в котором сказано как нужно именовать поля класса, методы и можно ли несколько полей/переменных объявлять на одной строке

- [x] 17. метод нарушает принцип единственно ответственности https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L123

- [x] 18. в одно файле должен быть один класс или энум https://github.com/Rq0/GL_proj1/blob/master/untitled/src/AAAService.java#L151

- [x] 19. класс нарушает принцип единственно ответственности, нужно разбить https://github.com/Rq0/GL_proj1/blob/master/untitled/src/Validator.java#L8

- [x] 20. DefaultParser https://github.com/Rq0/GL_proj1/blob/master/untitled/src/Validator.java#L18

- [x] 21. Можно получить список аргументов и взять количество  потом вызвать isEmpty https://commons.apache.org/proper/commons-cli/apidocs/org/apache/commons/cli/CommandLine.html#getArgList-- https://github.com/Rq0/GL_proj1/blob/master/untitled/src/Validator.java#L34

- [x] 22. Почему поля сделаны статиками? https://github.com/Rq0/GL_proj1/blob/master/untitled/src/Validator.java#L10

- [x] 23. у энумов есть метод fromString которы бросает исключение если такое энум не найден, исключение надо будет поймать и обработать https://github.com/Rq0/GL_proj1/blob/master/untitled/src/Validator.java#L63

**Comment by Rq0** [comment]
![image](https://cloud.githubusercontent.com/assets/20400834/23908099/a3551d34-0905-11e7-80cf-51765180749d.png)
![image](https://cloud.githubusercontent.com/assets/20400834/23908259/11eba498-0906-11e7-9a92-e1b072192c99.png)

**Comment by Rq0** [comment]
4. String занимает много места в памяти и представляет собой неизменяемые последовательности символов (новая строка создается), в отличие от StringBuilder и StringBuffer

**Comment by Rq0** [comment]
9. Если удалю одного из юзеров, то вместе с ним удалю записи по userId из ресурсов и аккаунтов и этого id больше не будет в базе, сдвигать все id на -1 после этого юзера не буду, оставлю как есть
